#!/usr/bin/env python3
from enum import Enum


class Event(Enum):
    NONE = 'NONE'
    DRAG = 'DRAG'
    DROP = 'DROP'
    FOCUS_IN = 'FOCUS_IN'
    FOCUS_OUT = 'FOCUS_OUT'
    MOUSE_BUTTON_PRESS = 'MOUSE_BUTTON_PRESS'
    MOUSE_BUTTON_RELEASE = 'MOUSE_BUTTON_RELEASE'
    MOUSE_DOUBLE_CLICK = 'MOUSE_DOUBLE_CLICK'
    MOUSE_HOVER_ENTER = 'MOUSE_HOVER_ENTER'
    MOUSE_HOVER_LEAVE = 'MOUSE_HOVER_LEAVE'
    MOUSE_HOVER_MOVE = 'MOUSE_HOVER_MOVE'
    MOUSE_RIGHT_CLICK = 'MOUSE_RIGHT_CLICK'
    MOUSE_WHEEL = 'MOUSE_WHEEL'
    RESIZE = 'RESIZE'
    # EVENT_FILTER

    def __str__(self):
        return f'<Event: {id(self)}>'
