#!/usr/bin/env python3
from enum import Enum


class Event(Enum):
    # EVENT_FILTER = 'EVENT_FILTER'
    FOCUS_IN = 'FOCUS_IN'
    FOCUS_OUT = 'FOCUS_OUT'
    HOVER_ENTER = 'HOVER_ENTER'
    HOVER_LEAVE = 'HOVER_LEAVE'
    HOVER_MOVE = 'HOVER_MOVE'
    MOUSE_CLICK = 'MOUSE_CLICK'
    MOUSE_DOUBLE_CLICK = 'MOUSE_DOUBLE_CLICK'
    MOUSE_RIGHT_CLICK = 'MOUSE_RIGHT_CLICK'
    MOUSE_WHEEL = 'MOUSE_WHEEL'
    NONE = 'NONE'
